# Copyright (C) 2026 Jean-Christophe Giret
# SPDX-License-Identifier: AGPL-3.0-or-later
# The database URL comes from MELLISCRIBE_DATABASE_URL (see db/session.py).
[alembic]
script_location = src/melliscribe/db/migrations
