"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-22 22:42:18.505470
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('audio_retention_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('llm_trace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('rates_checked_on', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fallback_taken', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_trace_created_at'), 'llm_trace', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_trace_recording_id'), 'llm_trace', ['recording_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('audio_format', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_available', sa.Boolean(), nullable=False),
    sa.Column('audio_key', sa.String(length=256), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_stage', sa.String(length=32), nullable=True),
    sa.Column('reprocess_failed', sa.Boolean(), nullable=False),
    sa.Column('eval_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_state'), 'recordings', ['state'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('language_detected', sa.String(length=2), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id')
    )
    op.create_table('inspection_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('hive_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id')
    )
    op.create_index(op.f('ix_inspection_records_hive_id'), 'inspection_records', ['hive_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_inspection_date'), 'inspection_records', ['inspection_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_records_inspection_date'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_hive_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_recordings_state'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_llm_trace_recording_id'), table_name='llm_trace')
    op.drop_index(op.f('ix_llm_trace_created_at'), table_name='llm_trace')
    op.drop_table('llm_trace')
    op.drop_table('hives')
    op.drop_table('account_settings')
    # ### end Alembic commands ###
